### ISSUE TITLE
Crash with Fluid Node

### ISSUE THREAD

**Issue by ChatFawkes** [thefjong2/Power-Nodes#3]
Had two EnderIO pressurized tanks. One with an output and input both next the fluid nodes. Placed liquid xp (from EnderIO) into the outputting tank and then the game crashed.

Here is the report: https://gist.github.com/ChatFawkes/64c4d91312aadd7f746e

Using version 1.1.2

**Comment by thefjong2** [comment]
Fixed ;).. Thanks !:)
